export const FETCH_DATA_FOR_CHART_REQUEST = 'FETCH_DATA_FOR_CHART_REQUEST';
export const FETCH_DATA_FOR_CHART_SUCCESS = 'FETCH_DATA_FOR_CHART_SUCCESS';
export const FETCH_DATA_FOR_CHART_FAIL = 'FETCH_DATA_FOR_CHART_FAIL';